--- #Install Telnet
- hosts: "{{ machine }}"
  become: yes
  become_method: sudo
  gather_facts: "{{ gather }}"
  vars:
   machine: xcapital
   gather: yes
   pkg: telnet.x86_64
   penya: latest
   vanish: absent
  tasks:
   - name: Uninstall telnet.x86_64
     yum: 
      name: "{{ pkg }}"
      state: "{{ vanish }}"
   - name: Install telnet.x86_64
     yum:
      name: "{{ pkg }}"
      state: "{{ penya }}"
     register: result
   - debug: var=result
