--- # Notofication and Handling events

- hosts: '{{ machine }}'
  become: yes
  become_method: sudo
  remote_user: user
  gather_facts: '{{ gather }}'
  vars:
   machine: xcapital
   gather: yes
   pkg: nginx.x86_64
   penya: latest
   running: restarted
  tasks:
   - name: Install ngingx
     yum:
      name: '{{ pkg }}'
      state: '{{ penya }}'
     notify:  
     - start nging service
  handlers:
   - name: start nging service
     service:
      name: nginx
      state: '{{ running }}'
     register: result
   - debug: var=result 
     
   
